//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int recordID { get; set; }
        public string cartID { get; set; }
        public int AlbumId { get; set; }
        public int count { get; set; }
        public System.DateTime createdDate { get; set; }
    
        public virtual Album Album { get; set; }
    }
}
