//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personInf
    {
        public int personID { get; set; }
        public string personName { get; set; }
        public string Surname { get; set; }
        public string address { get; set; }
    }
}
