//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoles
    {
        public int userRoleID { get; set; }
        public int userID { get; set; }
        public int roleId { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual User User { get; set; }
    }
}
